//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentSaleView
    {
        public Nullable<int> IdAgent { get; set; }
        public string AgentName { get; set; }
        public string Gender { get; set; }
        public string Login { get; set; }
        public System.DateTime DateClosure { get; set; }
        public string TypeTransaction { get; set; }
        public string PaymentForProperty { get; set; }
        public string BuyerName { get; set; }
    }
}
