//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonLivingProperty
    {
        public int IdNonLivingProperty { get; set; }
        public int IdProperty { get; set; }
        public int IdNonLivingPropertyType { get; set; }
        public decimal AreaSquareMeters { get; set; }
        public int ParkingSpaces { get; set; }
    
        public virtual NonLivingPropertyType NonLivingPropertyType { get; set; }
        public virtual Property Property { get; set; }
    }
}
