//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyView
    {
        public Nullable<int> IdProperty { get; set; }
        public string PropertyName { get; set; }
        public string PropertyDescription { get; set; }
        public string PropertyLocationName { get; set; }
        public string PropertyLocationDescription { get; set; }
        public Nullable<int> YearBuilt { get; set; }
        public Nullable<int> Floors { get; set; }
        public string HasElevator { get; set; }
        public Nullable<decimal> AreaSquareMeters { get; set; }
        public string LivingNonLivingType { get; set; }
        public Nullable<int> ParkingSpaces { get; set; }
        public Nullable<decimal> LivingAreaSquareMeters { get; set; }
        public Nullable<decimal> KitchenAreaSquareMeters { get; set; }
        public Nullable<int> RoomQuantity { get; set; }
        public Nullable<decimal> CeilingHeight { get; set; }
        public Nullable<int> FloorNumber { get; set; }
        public Nullable<byte> BathroomQuantity { get; set; }
        public string Adress { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
